### ISSUE TITLE
Add guideline for toleration injection into `node-feature-discovery` subchart

### ISSUE THREAD

**Issue by hoony9x-furiosa-ai** [furiosa-ai/helm-charts#17]
## Describe the feature

Sometimes we need to add toleration at the `node-feature-discovery` too.

## Describe the solution you'd like

Add injection guideline like below.

```yaml
node-feature-discovery:
  enabled: true
  worker:
    tolerations:
      - key: "rngd"
        operator: "Equal"
        effect: "NoSchedule"
```
- Above contents are in the `values.yaml` of `furiosa-feature-discovery` Helm chart.

## Describe alternatives you've considered

[//]: # (A clear and concise description of any alternative solutions or features you've considered.)

## Additional context

[//]: # (Please add any related issue or external link here.)
